### PR TITLE
[Easy] Remove flatMap from script parsing

### LINKED ISSUE #514: place_spread_order not working
```
npx truffle exec scripts/stablex/place_spread_orders.js --tokens 3,4,5,7 --accountId 0 --validFrom 4 --expiry 5266509 --sellAmount 50 --spread 2 --network rinkeby
> Warning: possible unsupported (undocumented in help) command line option: --tokens,--accountId,--validFrom,--expiry,--sellAmount,--spread
Using network 'rinkeby'.
Options:
  --tokens, -t                              Collection of trusted tokenIds
                                                              [array] [required]
  --accountId                               Account index of the order placer
                                                                      [required]
  --spread                                  Percentage increase required for
                                            trade (fees not accounted)
                                                                 [default: 0.25]
  --sellAmount                              Maximum sell amount (in full token
                                            units)               [default: 1000]
  --validFrom                               Number of batches (from current)
                                            until order become valid[default: 3]
  --expiry                                  Maximum auction batch for which
                                            these orders are valid
                                                           [default: 4294967295]
  --Make sure that you have an RPC          Show help
  connection to the network in
  consideration. For network
  configurations, please see
  truffle-config.js Example usage
  npx truffle exec
  scripts/stablex/place_spread_orders.js
  --tokens=2,3,4 --accountId 0 --spread
  0.3 --validFrom 5                                                    [boolean]
array.flatMap is not a function

```

### PR DESCRIPTION
**Pull request by bh2smith**
The previous place_spread_orders and cancel_orders scripts were parsing `[ 'i,j,k' ]` with flatMap which was not necessary and only worked on node v13. This update addresses that and closes #514. 

Test Plan:

```sh
 export PK=ac20fd13d9a7f9325262ce81c07b16b1c3f92be56da33789b831a8f6eaef9ef0 
npx truffle exec scripts/stablex/place_spread_orders.js --tokens=2,3,4,5,6 --accountId 0 --network rinkeby
```

Should result in 

```
> Warning: possible unsupported (undocumented in help) command line option: --tokens,--accountId
Using network 'rinkeby'.

Recovering token data from URL https://raw.githubusercontent.com/gnosis/dex-js/master/src/tokenList.json
Sell 1000000000000000000000 TUSD for 1002500000 USDT
Sell 1000000000 USDT for 1002499999999966445568 TUSD
Sell 1000000000 USDC for 1002500000 USDT
Sell 1000000000 USDT for 1002500000 USDC
Sell 1000000000000000000000 PAX for 1002500000 USDT
Sell 1000000000 USDT for 1002499999999966445568 PAX
Sell 100000 GUSD for 1002500000 USDT
Sell 1000000000 USDT for 100250 GUSD
Sell 1000000000 USDC for 1002499999999966445568 TUSD
Sell 1000000000000000000000 TUSD for 1002500000 USDC
Sell 1000000000000000000000 PAX for 1002499999999966445568 TUSD
Sell 1000000000000000000000 TUSD for 1002499999999966445568 PAX
Sell 100000 GUSD for 1002499999999966445568 TUSD
Sell 1000000000000000000000 TUSD for 100250 GUSD
Sell 1000000000000000000000 PAX for 1002500000 USDC
Sell 1000000000 USDC for 1002499999999966445568 PAX
Sell 100000 GUSD for 1002500000 USDC
Sell 1000000000 USDC for 100250 GUSD
Sell 100000 GUSD for 1002499999999966445568 PAX
Sell 1000000000000000000000 PAX for 100250 GUSD
Are you sure you want to send this transaction to the EVM? [yN] N
```

### CODE REVIEW

File: scripts/stablex/cancel_order.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ const argv = require("yargs")
     describe: "Order IDs to be canceled",
     coerce: array => {
       try {
-        return array.flatMap(v => v.split(",").map(o => parseInt(o)))
+        return array[0].split(",").map(o => parseInt(o))
```
Comment (fleupold) [inline scripts/stablex/cancel_order.js]: This only works if the array always only have 1 item. If this is the case it should probably not be an array in the first place but instead a string?

Comment (bh2smith) [reply scripts/stablex/cancel_order.js]: That makes sense. Although why would the array every have more than one Item... I will fix it nonetheless

**Review by nlordell — COMMENTED** [review]
I fell like this was already included in a separate PR.

> Note that #531 should be merged first.

**Review by josojo — APPROVED** [review]
thanks Ben!
