### PR TITLE
[Audit] Consume claimable withdraw 

### LINKED ISSUE #448: [Audit] SubtractBalance should respect available balance
Currently subtractBalance just SafeMath subtracts the requested amount from the net balance. However, part of this balance can already be reserved for "matured" withdraw requests and should thus be untouchable.

https://github.com/gnosis/dex-contracts/blob/a7149e93b6f383b06019415e6e5639885d6faeb8/contracts/EpochTokenLocker.sol#L208-L211

This allows an attacker to submit a "valid" solution, which taps into a user's matured withdraw amount. Benign solvers will ignore this amount and thus might be able to match less trades leading to a worse objective value.

The only defense would be to claim the withdraw immediately when it becomes available. Otherwise it will just be reduced to the remaining available amount.

To fix this issue, we should create a regression test demonstrating the attack and then insert the require statement into the method above.

### PR DESCRIPTION
**Pull request by bh2smith**
This PR introduces a regression test (example scenario) of an exploit discovered in the audit #448.

The Regression test is summarized as the following sequence of events/transactions:

1. **Deposit:** 
Two users about to trade deposit token 0 and 1 respectively.
2. **Request Withdraw:** 
User 0 requests to withdraw the full amount of recent deposit.
3. **Close Auction:** 
Wait until withdraw request becomes claimable.
4. **Place Orders:** 
Users place orders selling the full amount of their recent deposits (buying the opposite respective tokens) such that these two orders would directly match.
5. **Close Auction:** 
Solution is submitted matching the two above trade requests.
6. **Claim Traded Balance:** 
User 0 proceeds in claiming their valid withdraw request of their original deposited token that has already been traded.

Closes #448

### CODE REVIEW

File: test/stablex/regression_tests.js [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+
+      await makeDeposits(batchExchange, accounts, basicTrade.deposits)
+      const firstOrder = basicTrade.orders[0]
+      const tokenAddress = await batchExchange.tokenIdToAddressMap.call(firstOrder.sellToken)
+      const attackerAddress = accounts[firstOrder.user]
+
+      await batchExchange.requestWithdraw(tokenAddress, firstOrder.sellAmount, { from: attackerAddress })
+      await closeAuction(batchExchange)
+      // Ensure withdraw is claimable.
+      assert(batchExchange.hasValidWithdrawRequest.call(attackerAddress, tokenAddress), true)
```
Comment (fleupold) [inline test/stablex/regression_tests.js]: Also maybe assert that `getBalance()` returns 0 for  attackerAddress and tokenAddress.

File: test/stablex/regression_tests.js [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+        solution.owners,
+        solution.touchedorderIds,
+        solution.volumes,
+        solution.prices,
+        solution.tokenIdsForPrice,
+        { from: solver }
+      )
+      assert(objectiveValue > new BN(2).pow(new BN(128)))
+    })
+    it("Consume claimable withdraw balance", async () => {
```
Comment (fleupold) [inline test/stablex/regression_tests.js]: nit: Since this is supposed to read like a sentence, maybe rename to `it(Should not allow to use claimable withdraws in solution)`

**Review by fleupold — APPROVED** [review]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2FRNkTWc4A05bDa%2Fgiphy-downsized-medium.gif&token=precision_work" data-gitmeme-token="precision_work"></a>

File: test/stablex/regression_tests.js (hunk 2 above)
Comment (bh2smith) [reply test/stablex/regression_tests.js]: Yes sorry! I forgot.

File: test/stablex/regression_tests.js (hunk 1 above)
Comment (bh2smith) [reply test/stablex/regression_tests.js]: Also, I am surprised I didn't need to `await` this last call.
