### PR TITLE
Don't pop from accounts list

### LINKED ISSUE #487: Non-determinstic test failure
I have been seeing these two failing tests every once in a while:

```
  2 failing
  1) Contract: BatchExchange
       submitSolution()
         ensures half of the token imbalance (fees) is burned and that better solutions don't double-burn:
     Error: The send transactions "from" field must be defined!
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.deposit (node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at makeDeposits (test/stablex/stablex_utils.js:45:20)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  2) Contract: BatchExchange
       submitSolution()
         verifies the 2nd solution is correctly documented and can be reverted by a 3rd:
     Error: The send transactions "from" field must be defined!
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at TruffleContract.deposit (node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
      at makeDeposits (test/stablex/stablex_utils.js:45:20)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

They are often fixed by simply rerunning the test, but it seems strange.

**Example**

https://travis-ci.org/gnosis/dex-contracts/builds/639950058?utm_source=github_status&utm_medium=notification

### PR DESCRIPTION
**Pull request by fleupold**
Closes #487

Tests fail exclusively on advancedTrade which uses 5 different users. It looks like `from` is undefined in the failure cases. The from is taken from the global account list that is passed into the test suite. It turns out that we were popping and thus mutating that list in multiple places, which might cause this behaviour.

This PR replaces the mutating pop with a read and should just no longer drain the accounts array to a point where not enough accounts are left.

### CODE REVIEW

File: test/stablex/batch_exchange.js [hunk 1]
```diff
@@ -39,9 +39,7 @@ const smallTradeData = {
 }
 
 contract("BatchExchange", async accounts => {
-  const solver = accounts.pop()
-  const competingSolver = accounts.pop()
-  const [user_1, user_2, user_3] = accounts
+  const [user_1, user_2, user_3, solver, competingSolver] = accounts
```
Comment (bh2smith) [inline test/stablex/batch_exchange.js:42]: There was a reason we had done this in the past. This was introduced when @nlordell  and I setup the Example files. Perhaps it is no longer necessary.

**Review by bh2smith — APPROVED** [review]
Excellent catch. AlthoughI do recall this was necessary at one point. Perhaps it is no longer.
