### PR TITLE
Contract typings

### LINKED ISSUE #325: `dex-contract` NPM Module
After a discussion with @anxolin today we decided to create an NPM package for `dex-contracts` that can be consumed by packages who want to interact with the smart contract on the network. A couple additional utility functions should be made available as they are closely coupled with the contract code itself.

The NPM module will provide:
- [x] The contract ABI (#323)
- [x] Type definitions for use with TypeScript (for Web3js) (#435)
- [x] Utility functions for encoding/decoding parameters and return values (like decoding orders) (#323)

This means that the NPM package should not have any dependencies and should all become devDependencies with the exception of what is needed for the utility functions (I suspect BN.js will be needed).

### PR DESCRIPTION
**Pull request by nlordell**
Add type definitions for index module.

Closes #325

### CODE REVIEW

**Review by josojo — APPROVED** [review]
Looks all very good to me. 

But one of the "consumers of the type script files" should also approve

File: src/index.d.ts [hunk 1]
```diff
@@ -0,0 +1,67 @@
+export interface ContractAbiEntry {
```
Comment (anxolin) [inline src/index.d.ts:1]: What are these declarations?

**Review by anxolin — COMMENTED** [review]
I'm afraid this will have the same issue we experienced with the events not being.

We had to extend the autogenerated contract to redeclare the events properly.

Check out `src/contracts/BatchExchangeContract.ts` in `dex-js`.

If you can, generate a version so we can try if it works for us and we can adapt dex-js. I usually create a release candidate for these things:
`npm version prerelease --preid=RC`

File: src/index.d.ts (hunk 1 above)
Comment (bh2smith) [reply src/index.d.ts:1]: They are subtypes of the contract interface.

Comment (nlordell) [reply src/index.d.ts:1]: They are just some basic typings for the Truffle artifacts being exported.

**Comment by nlordell** [comment]
@anxolin  I am seeing the events being generated in the types:
```
  events: {
    OrderPlacement: ContractEvent<{
      owner: string;
      index: string;
      buyToken: string;
      sellToken: string;
      validFrom: string;
      validUntil: string;
      priceNumerator: string;
      priceDenominator: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: string;
      7: string;
    }>;
    OrderCancelation: ContractEvent<{
      owner: string;
      id: string;
      0: string;
      1: string;
    }>;
    // ...
  }
```

What is wrong with these events?

**edit**: I checked here and they look the same: https://github.com/gnosis/dex-js/blob/master/src/contracts/gen/BatchExchange.d.ts

**Comment by anxolin** [comment]
But this is what we export, we had to do this fix:
https://github.com/gnosis/dex-js/blob/master/src/contracts/Erc20Contract.ts#L6
https://github.com/gnosis/dex-js/blob/master/src/contracts/types.ts#L27

Maybe you see a way around that, but we redefined the events because it was not working for us.
My fix was a bit different, it was just redefining the events using the right event emitter from web3. Dima did this smart fix that simplified it's use, but I'm a bit lost on what these lines of typescript do


But let's do one thing, let's try if it works in `dex-js` and if it doesn't we see how to fix it.

File: src/index.d.ts (hunk 1 above)
Comment (anxolin) [reply src/index.d.ts:1]: Aha! cool. Would it be worth it to use some other NPM dependency for that. Maybe https://github.com/ethereum-ts/truffle-typings or https://www.npmjs.com/package/truffle-contract-typescript

Comment (nlordell) [reply src/index.d.ts:1]: Yes, It would be great to use an NPM dependency for that! However, these seem to be for using contracts with truffle. The type definitions are just for the truffle artifact JSON (the JSON files located at `build/contracts/*.json`) - we need this because we re-export the JSON documents.

This should go away once we start using TypeScript, since if you `tsc --declaration` they get get generated for you, so I am not too worried.

**Comment by nlordell** [comment]
That is some TypeScript black magic... Looks like some fancy footwork to replace the `gen/types.d.ts` `EventOptions` with `web3-eth-contracts` version of `EventOptions`. I may be reading it wrong though.

**Review by bh2smith — APPROVED** [review]
Fine!

**Comment by anxolin** [comment]
@nlordell let me know if we have to do a test for this as some point. I'll be on vacations next week, do you think we can test/close this?

**Comment by nlordell** [comment]
@anxolin I will release this version tomorrow. Sorry to keep you waiting but I wanted it to be deployed with the new auto-deploy on tag stuff that I had been working on but put it in the back-burner as Denis was on vacation last week. He is here now and we are scheduling some time tomorrow to sort it out.

**Comment by anxolin** [comment]
No worries, we are not blocked. We have our own typings. It was just since I'll be on vacations I'm cleaning the house before I leave

That's great news! Looking forward to see the autodeploy-tagging thing

**Comment by nlordell** [comment]
I'm going to merge this for now, and then revisit if there are any issues with the typings.
