### PR TITLE
Fixing migration flags

### LINKED ISSUE #320: Fix the migration flag --onlyMigrateStableX
For the rinkeby deployment, this flag is not passed on properly for some reason.

Also, proper documentation should be added

### PR DESCRIPTION
**Pull request by josojo**
Closes #320 

For some reason the way I exported argv was wrong. I really prefer to have argv out of the utilities.js, (as I am doing it in this PR) for easier readability.

---

testplan:
```
 npx truffle migrate --onlyMigrateStableX=true
```
And check that only stableX gets migrated

### CODE REVIEW

**Review by bh2smith — APPROVED** [review]
This is really great! I approve of less waste!

**Review by nlordell — APPROVED** [review]

File: migrations/4_stablecoin_converter.js [hunk 1]
```diff
@@ -1,7 +1,12 @@
-const argv = require("../src/migration_utilities")
 const migrateStablecoinConverter = require("../src/migration_scripts_stablecoinConverter/migrate_PoC_dfusion")
+const argv = require("yargs")
```
Comment (fleupold) [inline migrations/4_stablecoin_converter.js:2]: It would have had to be 

```js
const { argv } = require("../migration_utilities")
```

Right now it was an object with three fields (argv, getDependency, isDevelopmentNetwork)

**Review by fleupold — APPROVED** [review]
