### PR TITLE
[Test] Big Number Compatibility

### LINKED ISSUE #116: [Test Suite] Large numbers incorrectly interpreted in `encodeOrder`
When passing values such as

```
const order = encodeOrder(1, 0, 1,   100000000000000009) --> shows 100000000000000020   for last value
const order = encodeOrder(1, 0, 1,  1000000000000000009) --> shows 1000000000000000000  for last value
const order = encodeOrder(1, 0, 1, 10000000000000000009) --> shows 10000000000000000000 for last value
```
into `encodeOrder` shown here, we get very weird output/misinterpreted values. 

https://github.com/gnosis/dex-contracts/blob/351fc720b04d9b04555ac33307bab5213176340e/test/snapp_utils.js#L62-L64

### PR DESCRIPTION
**Pull request by bh2smith**
closes #116 

There is still a weird issue that `encodeOrder` doesn't allow us to pass amounts like `2**96 - 1` since JS evaluates 

```
2**96 as 7.922816251426434e+28 which is 79228162514264334000000000000
```
However
```
12**96 = 79228162514264337593543950336
```

This is not a major concern since it does not affect the contract code.

### CODE REVIEW

File: test/snapp_auction.js [hunk 1]
```diff
@@ -612,6 +613,16 @@ contract("SnappAuction", async (accounts) => {
       assert.equal(auctionIndex, 1)
     })
 
+    it("Large sell order", async () => {
+      const instance = await SnappAuction.new()
+      await setupEnvironment(MintableERC20, instance, token_owner, [user_1], 2)
+      const largeNumberString = "79228162514264333000000000000"  // compare with 2**96 = 7.922816251426434e+28
```
Comment (fleupold) [inline test/snapp_auction.js]: Shouldn't this be actually 2**96? (`79228162514264337593543950336`)

**Review by fleupold — APPROVED** [review]
> encodeOrder doesn't allow us to pass amounts like 2**96 - 1

You should be able to do

```js
const amount = new BN(2).pow(new BN(96)).sub(new BN(1))
```

File: test/snapp_auction.js (hunk 1 above)
Comment (bh2smith) [reply test/snapp_auction.js]: Please refer to the comment in the description.

Comment (fleupold) [reply test/snapp_auction.js]: So why not use `new BN(2).pow(new BN(96))` so that this also serves as documentation for someone looking to use this?

Comment (bh2smith) [reply test/snapp_auction.js]: Awesome thanks, worked like a charm.

**Review by josojo — APPROVED** [review]
Yes, makes perfect thanks.
Sweet sauce!
