### PR TITLE
Type descripency and mint bug

### LINKED ISSUE #830: [Bug] token minting ignored in setup_environment.ts
When writing a for `transitive_orderbook` migration [here](https://github.com/gnosis/dex-contracts/pull/828#issuecomment-637472413) I discovered that only the owl token had been minted to the accounts... After closer look at the following snippet, we see that `token.contract.methods.mint` is not working. This should be `token.mint`.

https://github.com/gnosis/dex-contracts/blob/735c370036971d82b434cb3b09c4ec849ef77d5a/scripts/setup_environment.ts#L45-L57

Furthermore, when attempting to fix this mistake, we realize that we have initialized a list containing two different types:

https://github.com/gnosis/dex-contracts/blob/2025c76ab8a96ff52f30ddbcbf649c4c4b589e1b/scripts/setup_environment.ts#L37-L43

That is, the first entry is `TokenOWLInstance` while all the others are `ERC20Mintable`

### PR DESCRIPTION
**Pull request by bh2smith**
Closes #830 

**Test Plan**

```sh
# T1: Run Ganache with gas limit 8e6
ganache-cli -l 8e6
# T2:  Migrate contracts
truffle migrate
npx truffle exec build/common/scripts/setup_environment.js 
npx truffle exec build/common/scripts/deposit.js --accountId i --tokenId j --amount 10
```

for all `i, j in {0, 1, 2}`.

### CODE REVIEW

File: scripts/setup_environment.ts [hunk 1]
```diff
@@ -44,13 +44,15 @@ module.exports = async function (callback: Truffle.ScriptCallback) {
...
     for (let account = 0; account < argv.numAccounts; account++) {
-      for (let token = 0; token < argv.numTokens; token++) {
-        if (token == 0) {
-          await owlProxy.mintOWL(accounts[account], amount);
-        } else {
-          await tokens[token].contract.methods.mint(accounts[account], amount);
-        }
-        await tokens[token].approve(instance.address, amount, {
+      // Mint and approve OWL
+      await owlProxy.mintOWL(accounts[account], amount);
```
Comment (nlordell) [inline scripts/setup_environment.ts:48]: tricky.... Its a different method!

**Review by nlordell — APPROVED** [review]
Nice catch!

File: scripts/setup_environment.ts (hunk 1 above)
Comment (bh2smith) [reply scripts/setup_environment.ts:48]: It is. I am now going to use my new found understanding here to deal with #822
